#!/usr/bin/env bash

set -e

name=$(basename "$(pwd)")

# Get all the submodules.
git submodule sync && git submodule update --init

# Clean up.
rm -rf vendor test/vendor go-client-template
make -C test clean-reports

# Replace name in files.
find "." -type f -exec sed -i "s/go-client-template/$name/g" {} +

# Override test files.
find "test" -type f -name "*.rb" -exec sed -i "s/Example/${name^}/g" {} +
find "test" -type f -name "*.rb" -exec sed -i "s/example/$name/g" {} +
mv "test/lib/example.rb" "test/lib/$name.rb"

# Fix style issues.
make dep && make format && make ruby-fix-lint

# Remove files that are not needed.
rm -rf "tools" "CHANGELOG.md"

# Create branch.
git checkout -b "$USER/feat/init" && make msg="init $name" commit push review
